import type { MahjongTileId } from './mahjong.ts'

export const DEFAULT_LOGO_URL = new URL('../assets/playcaptcha.svg', import.meta.url).href

export const DEFAULT_MAHJONG_URLS: Record<MahjongTileId, string> = {
  'wan-1': new URL('../assets/majiang_ui/21.webp', import.meta.url).href,
  'wan-2': new URL('../assets/majiang_ui/22.webp', import.meta.url).href,
  'wan-3': new URL('../assets/majiang_ui/23.webp', import.meta.url).href,
  'wan-4': new URL('../assets/majiang_ui/24.webp', import.meta.url).href,
  'wan-5': new URL('../assets/majiang_ui/25.webp', import.meta.url).href,
  'wan-6': new URL('../assets/majiang_ui/26.webp', import.meta.url).href,
  'wan-7': new URL('../assets/majiang_ui/27.webp', import.meta.url).href,
  'wan-8': new URL('../assets/majiang_ui/28.webp', import.meta.url).href,
  'wan-9': new URL('../assets/majiang_ui/29.webp', import.meta.url).href,
  'bamboo-1': new URL('../assets/majiang_ui/10.webp', import.meta.url).href,
  'bamboo-2': new URL('../assets/majiang_ui/11.webp', import.meta.url).href,
  'bamboo-3': new URL('../assets/majiang_ui/12.webp', import.meta.url).href,
  'bamboo-4': new URL('../assets/majiang_ui/13.webp', import.meta.url).href,
  'bamboo-5': new URL('../assets/majiang_ui/14.webp', import.meta.url).href,
  'bamboo-6': new URL('../assets/majiang_ui/15.webp', import.meta.url).href,
  'bamboo-7': new URL('../assets/majiang_ui/16.webp', import.meta.url).href,
  'bamboo-8': new URL('../assets/majiang_ui/17.webp', import.meta.url).href,
  'bamboo-9': new URL('../assets/majiang_ui/18.webp', import.meta.url).href,
  'circle-1': new URL('../assets/majiang_ui/32.webp', import.meta.url).href,
  'circle-2': new URL('../assets/majiang_ui/33.webp', import.meta.url).href,
  'circle-3': new URL('../assets/majiang_ui/34.webp', import.meta.url).href,
  'circle-4': new URL('../assets/majiang_ui/35.webp', import.meta.url).href,
  'circle-5': new URL('../assets/majiang_ui/36.webp', import.meta.url).href,
  'circle-6': new URL('../assets/majiang_ui/37.webp', import.meta.url).href,
  'circle-7': new URL('../assets/majiang_ui/38.webp', import.meta.url).href,
  'circle-8': new URL('../assets/majiang_ui/39.webp', import.meta.url).href,
  'circle-9': new URL('../assets/majiang_ui/40.webp', import.meta.url).href,
  east: new URL('../assets/majiang_ui/1.webp', import.meta.url).href,
  south: new URL('../assets/majiang_ui/2.webp', import.meta.url).href,
  west: new URL('../assets/majiang_ui/3.webp', import.meta.url).href,
  north: new URL('../assets/majiang_ui/4.webp', import.meta.url).href,
  red: new URL('../assets/majiang_ui/5.webp', import.meta.url).href,
  green: new URL('../assets/majiang_ui/6.webp', import.meta.url).href,
  white: new URL('../assets/majiang_ui/7.webp', import.meta.url).href,
}
